#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#словарь координат городов

sites = {
    'Moscow': (550, 370),
    'London': (510, 510),
    'Paris': (480, 480),
}

#функция для поиска расстояния между городами

def dis(x1, x2, y1, y2):
    return ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5

a = (sites['Moscow'] )
a1 = a[0]
a2 = a[1]
b = (sites['London'])
b1 = b[0]
b2 = b[1]
c = (sites['Paris'])
c1 = c[0]
c2 = c[1]

#словарь словарей расстояний между ними 

distances = dict(Moscow_London = dis(a1, b1, a2, b2),London_Paris = dis(b1, c1, b2, c2), Paris_Moscow = dis(a1, c1, a2, c2));

#вывод словаря

print(distances)
