#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Есть словарь координат городов

sites = {
    'Moscow': (550, 370),
    'London': (510, 510),
    'Paris': (480, 480),
}

# Составим словарь словарей расстояний между ними
# расстояние на координатной сетке - ((x1 - x2) ** 2 + (y1 - y2) ** 2) ** 0.5

distances = {
    'Moscow - London': (1), 
    'London - Paris': (2),
    'Paris - Moscow': (3),}
distances['Moscow - London'] = 

# TODO здесь заполнение словаря
print(sites)
print(distances)
