#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import simple_draw as sd
import random as rnd

sd.resolution = (1200, 600)

# Рисуем пузырек - три вложенных окружностей с шагом 5 пикселей

center = sd.Point(600, 500)
n = 40
while 40 <= n <= 50:
    sd.circle(center, n)
    n += 5

# Функция рисования пузырька, принимающая 4 параметра: точка рисования , шаг, количество вложенных окружностей и цвет


def bubble(point, radius, step, num, color):
    sd_point = sd.Point(*point)
    n = 1
    if num == 1:
        sd.circle(sd_point, radius, color)
    else:
        while num >= n:
            if n == 2:
                sd.circle(sd_point, radius - step, color)
            else:
                sd.circle(sd_point, radius - step * (n - 1), color)
            n += 1

# Рисуем 10 пузырьков в ряд

first_point = (90,90)
color = (255, 127, 0)
delta = 100
radius = 35
step = 5
num = 1
for number in range(10):
    point = (first_point[0] + number*delta, first_point[1])
    bubble(point, radius, step, num, color)

# Рисуем три ряда по 10 пузырьков

first_point = (90,200)
color = (255, 0, 0)
delta = 100
radius = 25
step = 5
num = 1
for number in range(10):
    x = 0
    while 130 >= x:
        point = (first_point[0] + number * delta, first_point[1] + x)
        bubble(point, radius, step, num, color)
        x += 65

# Рисуем 100 пузырьков в произвольных местах экрана случайными цветами

for i in range(100):
    bubble((rnd.randint(10,1290), rnd.randint(10,590)), 10, 3, 1, (rnd.randint(0,255), rnd.randint(0,255), rnd.randint(0,255)))

sd.pause()
