#!/usr/bin/env python3
# -*- coding: utf-8 -*-

user_input = input("Введите номер месяца: ")
month = int(user_input)
print('Вы ввели', month)
if month < 1 or month > 12:
    print('Такого месяца не существует, попробуйте ввести другое число')

elif month == 2:
    print('В данном месяце', 28, 'дней')
elif 0 < month <= 7:
    print('В данном месяце', 30, 'дней') if month % 2 == 0 else print('В данном месяце', 31, 'день')
elif month > 7:
    print('В данном месяце', 31, 'день') if month % 2 == 0 else print('В данном месяце', 30, 'дней')
