#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import simple_draw as sd
sd.resolution = (500, 500)

rainbow_colors = (sd.COLOR_RED, sd.COLOR_ORANGE, sd.COLOR_YELLOW, sd.COLOR_GREEN, sd.COLOR_CYAN, sd.COLOR_BLUE, sd.COLOR_PURPLE)

step = 5
start_x, end_x = 50, 350
start_y, end_y = 50, 450
i = 1

for i in range(7):
    start_x += step
    end_x += step
    sd.line(start_point = sd.get_point(start_x, start_y), end_point = sd.get_point(end_x, end_y), color = rainbow_colors[i], width = 4)
    i += 1
    print(i)

# Подсказка: цикл нужно делать сразу по тьюплу с цветами радуги.


# Усложненное задание, делать по желанию.
# Нарисовать радугу дугами от окружности (cсм sd.circle) за нижним краем экрана,
# поэкспериментировать с параметрами, что бы было красиво
# TODO здесь ваш код

sd.pause()
