#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# (цикл for)
import simple_draw as sd

brick_color = sd.COLOR_WHITE
step = 0

for y in range(0, 1000, 50):
    y1 = y + 50
    step -= 50
    for x in range(step, 1000, 100):
        x1 = x + 100
        left_bottom = sd.Point(x, y)
        right_top = sd.Point(x1, y1)
        sd.rectangle(left_bottom, right_top, color=brick_color, width=3)

sd.pause()
