#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import simple_draw
import random as rnd

simple_draw.resolution = (1000, 600)
smile_color = simple_draw.COLOR_CYAN


def smile(smile_x, smile_y, color):
    center = simple_draw.Point(smile_x, smile_y)
    simple_draw.circle(center, radius=50, color=color, width=1)
    center_1 = simple_draw.Point(smile_x - 25, smile_y + 6)
    simple_draw.circle(center_1, radius=10, color=color, width=1)
    center_1 = simple_draw.Point(smile_x + 25, smile_y + 6)
    simple_draw.circle(center_1, radius=10, color=color, width=1)
    center_1 = simple_draw.Point(smile_x - 25, smile_y + 6)
    simple_draw.circle(center_1, radius=2, color=color, width=1)
    center_1 = simple_draw.Point(smile_x + 25, smile_y + 6)
    simple_draw.circle(center_1, radius=2, color=color, width=1)
    center_1 = simple_draw.Point(smile_x, smile_y - 25)
    simple_draw.circle(center_1, radius=14, color=color, width=1)
    simple_draw.line(start_point=simple_draw.Point(smile_x + 10, smile_y + 30),
                     end_point=simple_draw.Point(smile_x + 30, smile_y + 20), color=color, width=1)
    simple_draw.line(start_point=simple_draw.Point(smile_x - 10, smile_y + 30),
                     end_point=simple_draw.Point(smile_x - 30, smile_y + 20), color=color, width=1)


for i in range(10):
    smile(rnd.randint(50, 950), rnd.randint(50, 550), smile_color)
    i += 1

simple_draw.pause()
