#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Убывающий факториал от n глубины k.
def falling(n, k):
    f = n
    i = 2
    if k == 0:
        print(1)
    else:
        while i <= k:
            f = f * (n - 1)
            i += 1
            n -= 1
        return print(f)

  #
  #      >>> falling(6, 3)  # 6 * 5 * 4
  #      120
  #      >>> falling(4, 3)  # 4 * 3 * 2
  #      24
  #       >>> falling(4, 1)  # 4
  #       4
  #      >>> falling(4, 0)
  #       1


#Сложить все цифры числа y
def sum_digits(y):
    num = int(y)
    sum = 0
    while (num != 0):
        sum = sum + num % 10
        num = num // 10
    print(sum)

#    >>> sum_digits(10) # 1 + 0 = 1
#    1
 #   >>> sum_digits(4224) # 4 + 2 + 2 + 4 = 12
# #   12
  #  >>> sum_digits(1234567890)
 #   45
  #  >>> a = sum_digits(123)
  #  >>> a
 #   6
 #   """
 #   "*** YOUR CODE HERE ***"

#Возвращает True если в n есть две цифры 8 подряд
def double_eights(n):
    if '88' in str(n):
        f = True
    else:
        f = False
    return print(f)

#   >>> double_eights(8)
#   False
#  >>> double_eights(88)
#   True
#   >>> double_eights(2882)
#   True
#   >>> double_eights(880088)
#   True
#   >>> double_eights(12345)
#  False
#  >>> double_eights(80808080)
#    False
